[package]
name = "zillion"
version = "0.5.0"
authors = ["rubyist <rubyist.personal@protonmail.com>"]

[dependencies]
googology = "0.2.0"
clap = "~2.33.0"

[profile.release]
lto=true
opt-level=3
panic='abort'
